import { bigint, integer, timestamp } from 'drizzle-orm/pg-core';

// Reusable column builders for the conventions shared across tables (entities.md
// "Conventions"). The table's property KEY names the column (snake_cased via the
// drizzle `casing` setting), so these helpers only carry type + modifiers.

/** bigint GENERATED BY DEFAULT AS IDENTITY primary key. */
export const idPk = () =>
  bigint({ mode: 'number' }).primaryKey().generatedByDefaultAsIdentity();

/** timestamptz NOT NULL DEFAULT now(). */
export const createdAt = () =>
  timestamp({ withTimezone: true }).notNull().defaultNow();

/** timestamptz NOT NULL DEFAULT now() (touch on update in the repository layer). */
export const updatedAt = () =>
  timestamp({ withTimezone: true }).notNull().defaultNow();

/** Nullable soft-delete marker. */
export const deletedAt = () => timestamp({ withTimezone: true });

/** Optimistic-concurrency token. */
export const version = () => integer().notNull().default(1);
