CREATE TYPE "public"."category_color" AS ENUM('pink', 'blue', 'amber', 'brand', 'violet', 'indigo', 'teal', 'red');--> statement-breakpoint
CREATE TYPE "public"."event_bucket" AS ENUM('active', 'completed');--> statement-breakpoint
CREATE TYPE "public"."event_status" AS ENUM('draft', 'planned', 'upcoming', 'live', 'completed', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."event_type" AS ENUM('Conference', 'Networking', 'Workshop', 'Charity & Gala', 'Sports & Wellness', 'Concert & Festival', 'Exhibition', 'Seminar');--> statement-breakpoint
CREATE TYPE "public"."seating_mode" AS ENUM('reserved', 'ga');--> statement-breakpoint
CREATE TYPE "public"."template_id" AS ENUM('aurora', 'noir', 'minimal', 'atlas');--> statement-breakpoint
CREATE TYPE "public"."visibility" AS ENUM('private', 'unlisted', 'public');--> statement-breakpoint
CREATE TABLE "categories" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"icon" text NOT NULL,
	"color" "category_color" NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_categories_org_name" UNIQUE("organization_id","name")
);
--> statement-breakpoint
CREATE TABLE "events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" bigint NOT NULL,
	"slug" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"type" "event_type" NOT NULL,
	"status" "event_status" DEFAULT 'draft' NOT NULL,
	"bucket" "event_bucket" NOT NULL,
	"visibility" "visibility" DEFAULT 'private' NOT NULL,
	"category_id" bigint,
	"start_at" timestamp with time zone NOT NULL,
	"end_at" timestamp with time zone,
	"timezone" text DEFAULT 'Asia/Bangkok' NOT NULL,
	"venue_name" text,
	"venue_address" text,
	"city" text,
	"is_online" boolean DEFAULT false NOT NULL,
	"online_note" text,
	"seating_mode" "seating_mode" DEFAULT 'ga' NOT NULL,
	"capacity" integer,
	"cover_image" text,
	"accent_color" text,
	"organizer_name" text NOT NULL,
	"contact_email" "citext",
	"landing_template_id" "template_id",
	"published_at" timestamp with time zone,
	"cancelled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by" uuid,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_events_org_slug" UNIQUE("organization_id","slug")
);
--> statement-breakpoint
CREATE TABLE "landing_templates" (
	"id" "template_id" PRIMARY KEY NOT NULL,
	"title" text NOT NULL,
	"badge" text NOT NULL,
	"description" text NOT NULL
);
--> statement-breakpoint
ALTER TABLE "categories" ADD CONSTRAINT "categories_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_landing_template_id_landing_templates_id_fk" FOREIGN KEY ("landing_template_id") REFERENCES "public"."landing_templates"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "events" ADD CONSTRAINT "events_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_categories_org" ON "categories" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "ix_events_org_status" ON "events" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "ix_events_start_at" ON "events" USING btree ("start_at");--> statement-breakpoint
CREATE INDEX "ix_events_type" ON "events" USING btree ("type");--> statement-breakpoint
CREATE INDEX "ix_events_category" ON "events" USING btree ("category_id");