CREATE TYPE "public"."session_color" AS ENUM('green', 'amber', 'rose');--> statement-breakpoint
CREATE TYPE "public"."session_type" AS ENUM('Keynote', 'Talk', 'Workshop', 'Panel', 'Break');--> statement-breakpoint
CREATE TYPE "public"."speaker_tone" AS ENUM('green', 'blue', 'purple', 'amber', 'red', 'pink');--> statement-breakpoint
CREATE TABLE "session_speakers" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "session_speakers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"session_id" uuid NOT NULL,
	"speaker_id" uuid NOT NULL,
	"sort_order" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "uq_session_speakers" UNIQUE("session_id","speaker_id")
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" bigint NOT NULL,
	"event_id" uuid NOT NULL,
	"day" smallint NOT NULL,
	"start_time" time NOT NULL,
	"end_time" time,
	"title" text NOT NULL,
	"type" "session_type" NOT NULL,
	"room" text,
	"color" "session_color",
	"sort_order" integer DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "ck_sessions_time" CHECK ("sessions"."end_time" IS NULL OR "sessions"."end_time" > "sessions"."start_time")
);
--> statement-breakpoint
CREATE TABLE "speakers" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" bigint NOT NULL,
	"event_id" uuid NOT NULL,
	"name" text NOT NULL,
	"role" text,
	"email" "citext",
	"phone" text,
	"talk_title" text,
	"tag" text,
	"initials" text,
	"tone" "speaker_tone",
	"rating" numeric(3, 2),
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
ALTER TABLE "session_speakers" ADD CONSTRAINT "session_speakers_session_id_sessions_id_fk" FOREIGN KEY ("session_id") REFERENCES "public"."sessions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "session_speakers" ADD CONSTRAINT "session_speakers_speaker_id_speakers_id_fk" FOREIGN KEY ("speaker_id") REFERENCES "public"."speakers"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "speakers" ADD CONSTRAINT "speakers_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "speakers" ADD CONSTRAINT "speakers_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_session_speakers_session" ON "session_speakers" USING btree ("session_id");--> statement-breakpoint
CREATE INDEX "ix_session_speakers_speaker" ON "session_speakers" USING btree ("speaker_id");--> statement-breakpoint
CREATE INDEX "ix_sessions_event_day" ON "sessions" USING btree ("event_id","day");--> statement-breakpoint
CREATE INDEX "ix_sessions_org" ON "sessions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "ix_speakers_event" ON "speakers" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "ix_speakers_org" ON "speakers" USING btree ("organization_id");