CREATE TYPE "public"."attendee_tag" AS ENUM('VIP', 'Speaker', 'Sponsor', 'Student');--> statement-breakpoint
CREATE TYPE "public"."hold_status" AS ENUM('active', 'converted', 'expired', 'released');--> statement-breakpoint
CREATE TYPE "public"."issued_ticket_status" AS ENUM('issued', 'checked_in', 'void', 'refunded', 'transferred');--> statement-breakpoint
CREATE TYPE "public"."order_status" AS ENUM('confirmed', 'pending', 'waitlisted', 'cancelled');--> statement-breakpoint
CREATE TYPE "public"."payment_method" AS ENUM('Card', 'PromptPay', 'Bank transfer');--> statement-breakpoint
CREATE TYPE "public"."payment_status" AS ENUM('paid', 'pending', 'refunded', 'failed');--> statement-breakpoint
CREATE TYPE "public"."refund_status" AS ENUM('pending', 'succeeded', 'failed');--> statement-breakpoint
CREATE TABLE "attendees" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attendees_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"name" text NOT NULL,
	"email" "citext" NOT NULL,
	"phone" text,
	"company" text,
	"job_role" text,
	"tag" "attendee_tag",
	"initials" text,
	"first_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_attendees_org_email" UNIQUE("organization_id","email")
);
--> statement-breakpoint
CREATE TABLE "order_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "order_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"order_id" uuid NOT NULL,
	"ticket_type_id" uuid NOT NULL,
	"quantity" smallint NOT NULL,
	"unit_price_satang" bigint NOT NULL,
	"line_subtotal_satang" bigint NOT NULL,
	"currency" char(3) DEFAULT 'THB' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_order_items_order_ticket_type" UNIQUE("order_id","ticket_type_id"),
	CONSTRAINT "ck_order_items_qty" CHECK ("order_items"."quantity" >= 1)
);
--> statement-breakpoint
CREATE TABLE "orders" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" bigint NOT NULL,
	"reference" text NOT NULL,
	"event_id" uuid NOT NULL,
	"attendee_id" bigint,
	"buyer_name" text NOT NULL,
	"buyer_email" "citext" NOT NULL,
	"buyer_phone" text,
	"status" "order_status" DEFAULT 'pending' NOT NULL,
	"payment_status" "payment_status" DEFAULT 'pending' NOT NULL,
	"seats" smallint NOT NULL,
	"subtotal_satang" bigint NOT NULL,
	"discount_code_id" uuid,
	"discount_amount_satang" bigint DEFAULT 0 NOT NULL,
	"vat_amount_satang" bigint DEFAULT 0 NOT NULL,
	"total_satang" bigint NOT NULL,
	"currency" char(3) DEFAULT 'THB' NOT NULL,
	"registered_at" timestamp with time zone DEFAULT now() NOT NULL,
	"cancelled_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by" uuid,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_orders_org_reference" UNIQUE("organization_id","reference"),
	CONSTRAINT "ck_orders_seats" CHECK ("orders"."seats" BETWEEN 1 AND 8),
	CONSTRAINT "ck_orders_money" CHECK ("orders"."subtotal_satang" >= 0 AND "orders"."discount_amount_satang" >= 0 AND "orders"."vat_amount_satang" >= 0 AND "orders"."total_satang" >= 0)
);
--> statement-breakpoint
CREATE TABLE "seat_assignments" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seat_assignments_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"seat_id" bigint NOT NULL,
	"ticket_id" uuid NOT NULL,
	"assigned_at" timestamp with time zone DEFAULT now() NOT NULL,
	"released_at" timestamp with time zone,
	CONSTRAINT "uq_seat_assignments_ticket" UNIQUE("ticket_id")
);
--> statement-breakpoint
CREATE TABLE "seat_holds" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "seat_holds_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"event_id" uuid NOT NULL,
	"order_id" uuid,
	"ticket_type_id" uuid,
	"seat_id" bigint,
	"quantity" integer DEFAULT 1 NOT NULL,
	"status" "hold_status" DEFAULT 'active' NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "tickets" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" bigint NOT NULL,
	"order_id" uuid NOT NULL,
	"order_item_id" bigint NOT NULL,
	"event_id" uuid NOT NULL,
	"ticket_type_id" uuid NOT NULL,
	"attendee_id" bigint,
	"qr_token" text NOT NULL,
	"holder_name" text,
	"ticket_label" text,
	"status" "issued_ticket_status" DEFAULT 'issued' NOT NULL,
	"checked_in_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_tickets_qr_token" UNIQUE("qr_token")
);
--> statement-breakpoint
CREATE TABLE "payments" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" bigint NOT NULL,
	"txn" text NOT NULL,
	"order_id" uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"payer_name" text NOT NULL,
	"method" "payment_method" NOT NULL,
	"amount_satang" bigint NOT NULL,
	"currency" char(3) DEFAULT 'THB' NOT NULL,
	"status" "payment_status" DEFAULT 'pending' NOT NULL,
	"paid_at" timestamp with time zone,
	"gateway_ref" text,
	"statement_descriptor" varchar(22),
	"fee_amount_satang" bigint,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_payments_org_txn" UNIQUE("organization_id","txn"),
	CONSTRAINT "uq_payments_org_idem" UNIQUE("organization_id","idempotency_key")
);
--> statement-breakpoint
CREATE TABLE "refunds" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" bigint NOT NULL,
	"payment_id" uuid NOT NULL,
	"order_id" uuid NOT NULL,
	"amount_satang" bigint NOT NULL,
	"currency" char(3) DEFAULT 'THB' NOT NULL,
	"reason" text,
	"status" "refund_status" DEFAULT 'pending' NOT NULL,
	"issued_by" uuid NOT NULL,
	"issued_at" timestamp with time zone DEFAULT now() NOT NULL,
	"gateway_ref" text,
	"idempotency_key" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_refunds_org_idem" UNIQUE("organization_id","idempotency_key")
);
--> statement-breakpoint
ALTER TABLE "attendees" ADD CONSTRAINT "attendees_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "order_items" ADD CONSTRAINT "order_items_ticket_type_id_ticket_types_id_fk" FOREIGN KEY ("ticket_type_id") REFERENCES "public"."ticket_types"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_attendee_id_attendees_id_fk" FOREIGN KEY ("attendee_id") REFERENCES "public"."attendees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_created_by_users_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignments" ADD CONSTRAINT "seat_assignments_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignments" ADD CONSTRAINT "seat_assignments_seat_id_seats_id_fk" FOREIGN KEY ("seat_id") REFERENCES "public"."seats"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_assignments" ADD CONSTRAINT "seat_assignments_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_holds" ADD CONSTRAINT "seat_holds_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_holds" ADD CONSTRAINT "seat_holds_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_holds" ADD CONSTRAINT "seat_holds_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_holds" ADD CONSTRAINT "seat_holds_ticket_type_id_ticket_types_id_fk" FOREIGN KEY ("ticket_type_id") REFERENCES "public"."ticket_types"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "seat_holds" ADD CONSTRAINT "seat_holds_seat_id_seats_id_fk" FOREIGN KEY ("seat_id") REFERENCES "public"."seats"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_order_item_id_order_items_id_fk" FOREIGN KEY ("order_item_id") REFERENCES "public"."order_items"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_ticket_type_id_ticket_types_id_fk" FOREIGN KEY ("ticket_type_id") REFERENCES "public"."ticket_types"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tickets" ADD CONSTRAINT "tickets_attendee_id_attendees_id_fk" FOREIGN KEY ("attendee_id") REFERENCES "public"."attendees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payments" ADD CONSTRAINT "payments_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refunds" ADD CONSTRAINT "refunds_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refunds" ADD CONSTRAINT "refunds_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refunds" ADD CONSTRAINT "refunds_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "refunds" ADD CONSTRAINT "refunds_issued_by_users_id_fk" FOREIGN KEY ("issued_by") REFERENCES "public"."users"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_attendees_org" ON "attendees" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "ix_attendees_tag" ON "attendees" USING btree ("organization_id","tag");--> statement-breakpoint
CREATE INDEX "ix_order_items_order" ON "order_items" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ix_order_items_ticket_type" ON "order_items" USING btree ("ticket_type_id");--> statement-breakpoint
CREATE INDEX "ix_orders_event" ON "orders" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "ix_orders_attendee" ON "orders" USING btree ("attendee_id");--> statement-breakpoint
CREATE INDEX "ix_orders_status" ON "orders" USING btree ("organization_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_seat_active" ON "seat_assignments" USING btree ("seat_id") WHERE "seat_assignments"."released_at" IS NULL;--> statement-breakpoint
CREATE INDEX "ix_seat_assignments_seat" ON "seat_assignments" USING btree ("seat_id");--> statement-breakpoint
CREATE INDEX "ix_seat_assignments_ticket" ON "seat_assignments" USING btree ("ticket_id");--> statement-breakpoint
CREATE UNIQUE INDEX "uq_seat_hold_active" ON "seat_holds" USING btree ("seat_id") WHERE "seat_holds"."status" = 'active';--> statement-breakpoint
CREATE INDEX "ix_seat_holds_expiry" ON "seat_holds" USING btree ("expires_at") WHERE "seat_holds"."status" = 'active';--> statement-breakpoint
CREATE INDEX "ix_seat_holds_order" ON "seat_holds" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ix_tickets_order" ON "tickets" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ix_tickets_event" ON "tickets" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "ix_tickets_attendee" ON "tickets" USING btree ("attendee_id");--> statement-breakpoint
CREATE INDEX "ix_tickets_status" ON "tickets" USING btree ("event_id","status");--> statement-breakpoint
CREATE INDEX "ix_payments_order" ON "payments" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ix_payments_event" ON "payments" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "ix_payments_status" ON "payments" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "ix_refunds_payment" ON "refunds" USING btree ("payment_id");--> statement-breakpoint
CREATE INDEX "ix_refunds_order" ON "refunds" USING btree ("order_id");