CREATE TYPE "public"."payment_connection_status" AS ENUM('disconnected', 'connected');--> statement-breakpoint
CREATE TYPE "public"."payment_mode" AS ENUM('test', 'live');--> statement-breakpoint
CREATE TYPE "public"."payment_provider" AS ENUM('stripe');--> statement-breakpoint
ALTER TYPE "public"."payment_method" ADD VALUE 'Apple Pay';--> statement-breakpoint
ALTER TYPE "public"."payment_method" ADD VALUE 'Google Pay';--> statement-breakpoint
CREATE TABLE "payment_method_settings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_method_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"method" "payment_method" NOT NULL,
	"enabled" boolean DEFAULT false NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_payment_method_settings_org_method" UNIQUE("organization_id","method")
);
--> statement-breakpoint
CREATE TABLE "payment_settings" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payment_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"provider" "payment_provider" DEFAULT 'stripe' NOT NULL,
	"mode" "payment_mode" DEFAULT 'test' NOT NULL,
	"status" "payment_connection_status" DEFAULT 'disconnected' NOT NULL,
	"account_id" text,
	"publishable_key" text,
	"connected_at" timestamp with time zone,
	"disconnected_at" timestamp with time zone,
	"default_currency" char(3) DEFAULT 'THB' NOT NULL,
	"statement_descriptor" varchar(22),
	"save_cards" boolean DEFAULT false NOT NULL,
	"email_receipts" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_payment_settings_org" UNIQUE("organization_id")
);
--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "address" text;--> statement-breakpoint
ALTER TABLE "organizations" ADD COLUMN "website" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "phone" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "timezone" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN "pending_email" "citext";--> statement-breakpoint
ALTER TABLE "payment_method_settings" ADD CONSTRAINT "payment_method_settings_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payment_settings" ADD CONSTRAINT "payment_settings_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;