CREATE TYPE "public"."social_provider" AS ENUM('google', 'apple', 'linkedin');--> statement-breakpoint
CREATE TABLE "social_identities" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "social_identities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"user_id" uuid NOT NULL,
	"provider" "social_provider" NOT NULL,
	"subject" text NOT NULL,
	"email" "citext",
	"linked_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_used_at" timestamp with time zone,
	CONSTRAINT "uq_social_identities_provider_subject" UNIQUE("provider","subject"),
	CONSTRAINT "uq_social_identities_user_provider" UNIQUE("user_id","provider")
);
--> statement-breakpoint
ALTER TABLE "social_identities" ADD CONSTRAINT "social_identities_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "social_identities" ADD CONSTRAINT "social_identities_user_id_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_social_identities_user" ON "social_identities" USING btree ("user_id");