CREATE TYPE "public"."discount_status" AS ENUM('active', 'scheduled', 'expired', 'disabled');--> statement-breakpoint
CREATE TYPE "public"."discount_type" AS ENUM('percent', 'fixed');--> statement-breakpoint
CREATE TABLE "discount_codes" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" bigint NOT NULL,
	"event_id" uuid,
	"code" text NOT NULL,
	"type" "discount_type" NOT NULL,
	"value" integer NOT NULL,
	"status" "discount_status" DEFAULT 'scheduled' NOT NULL,
	"used" integer DEFAULT 0 NOT NULL,
	"redemption_limit" integer DEFAULT 0 NOT NULL,
	"per_person_limit" integer DEFAULT 0 NOT NULL,
	"min_order_satang" bigint DEFAULT 0 NOT NULL,
	"valid_from" timestamp with time zone,
	"valid_until" timestamp with time zone,
	"revenue_attributed_satang" bigint DEFAULT 0 NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_discount_codes_org_event_code" UNIQUE("organization_id","event_id","code"),
	CONSTRAINT "ck_discount_codes_used" CHECK ("discount_codes"."used" >= 0),
	CONSTRAINT "ck_discount_codes_limit" CHECK ("discount_codes"."redemption_limit" >= 0),
	CONSTRAINT "ck_discount_codes_per_person" CHECK ("discount_codes"."per_person_limit" >= 0),
	CONSTRAINT "ck_discount_codes_min_order" CHECK ("discount_codes"."min_order_satang" >= 0),
	CONSTRAINT "ck_discount_codes_value" CHECK (("discount_codes"."type" = 'percent' AND "discount_codes"."value" BETWEEN 1 AND 100) OR ("discount_codes"."type" = 'fixed' AND "discount_codes"."value" >= 1))
);
--> statement-breakpoint
CREATE TABLE "discount_redemptions" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "discount_redemptions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"discount_code_id" uuid NOT NULL,
	"order_id" uuid NOT NULL,
	"buyer_email" "citext" NOT NULL,
	"amount_satang" bigint NOT NULL,
	"redeemed_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_discount_redemptions_code_order" UNIQUE("discount_code_id","order_id"),
	CONSTRAINT "ck_discount_redemptions_amount" CHECK ("discount_redemptions"."amount_satang" >= 0)
);
--> statement-breakpoint
ALTER TABLE "discount_codes" ADD CONSTRAINT "discount_codes_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discount_codes" ADD CONSTRAINT "discount_codes_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discount_redemptions" ADD CONSTRAINT "discount_redemptions_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discount_redemptions" ADD CONSTRAINT "discount_redemptions_discount_code_id_discount_codes_id_fk" FOREIGN KEY ("discount_code_id") REFERENCES "public"."discount_codes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "discount_redemptions" ADD CONSTRAINT "discount_redemptions_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_discount_codes_event" ON "discount_codes" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "ix_discount_codes_org" ON "discount_codes" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "ix_discount_redemptions_code" ON "discount_redemptions" USING btree ("discount_code_id");--> statement-breakpoint
CREATE INDEX "ix_discount_redemptions_order" ON "discount_redemptions" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ix_discount_redemptions_buyer" ON "discount_redemptions" USING btree ("discount_code_id","buyer_email");--> statement-breakpoint
ALTER TABLE "orders" ADD CONSTRAINT "orders_discount_code_id_discount_codes_id_fk" FOREIGN KEY ("discount_code_id") REFERENCES "public"."discount_codes"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_orders_discount" ON "orders" USING btree ("discount_code_id");