CREATE TYPE "public"."message_channel" AS ENUM('email', 'sms');--> statement-breakpoint
CREATE TABLE "message_templates" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "message_templates_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"slug" text NOT NULL,
	"title" text NOT NULL,
	"description" text,
	"channels" "message_channel"[] DEFAULT '{"email"}' NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"tags" text[] DEFAULT '{}' NOT NULL,
	"email_subject_en" text,
	"email_subject_th" text,
	"email_body_en" text,
	"email_body_th" text,
	"sms_body_en" text,
	"sms_body_th" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_message_templates_org_slug" UNIQUE("organization_id","slug")
);
--> statement-breakpoint
ALTER TABLE "events" ADD COLUMN "locale" "locale";--> statement-breakpoint
ALTER TABLE "message_templates" ADD CONSTRAINT "message_templates_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_message_templates_org" ON "message_templates" USING btree ("organization_id");