CREATE TYPE "public"."invoice_status" AS ENUM('issued', 'paid', 'overdue', 'void');--> statement-breakpoint
CREATE TYPE "public"."payout_status" AS ENUM('scheduled', 'processing', 'paid', 'failed');--> statement-breakpoint
CREATE TYPE "public"."tax_status" AS ENUM('upcoming', 'due', 'filed');--> statement-breakpoint
CREATE TABLE "invoices" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "invoices_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"number" text NOT NULL,
	"order_id" uuid NOT NULL,
	"event_id" uuid NOT NULL,
	"buyer_name" text NOT NULL,
	"issued_at" date NOT NULL,
	"due_at" date NOT NULL,
	"subtotal_satang" bigint NOT NULL,
	"vat_amount_satang" bigint NOT NULL,
	"amount_satang" bigint NOT NULL,
	"currency" char(3) DEFAULT 'THB' NOT NULL,
	"status" "invoice_status" DEFAULT 'issued' NOT NULL,
	"paid_via" "payment_method",
	"paid_on" date,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_invoices_org_number" UNIQUE("organization_id","number")
);
--> statement-breakpoint
CREATE TABLE "payout_items" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payout_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"payout_id" bigint NOT NULL,
	"payment_id" uuid NOT NULL,
	"gross_satang" bigint NOT NULL,
	"refund_satang" bigint DEFAULT 0 NOT NULL,
	"fee_satang" bigint DEFAULT 0 NOT NULL,
	"net_satang" bigint NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_payout_items_payout_payment" UNIQUE("payout_id","payment_id"),
	CONSTRAINT "uq_payout_items_payment" UNIQUE("payment_id")
);
--> statement-breakpoint
CREATE TABLE "payouts" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "payouts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"reference" text NOT NULL,
	"amount_satang" bigint NOT NULL,
	"currency" char(3) DEFAULT 'THB' NOT NULL,
	"bank_account" text NOT NULL,
	"status" "payout_status" DEFAULT 'scheduled' NOT NULL,
	"period_covered" text,
	"event_id" uuid,
	"requested_at" timestamp with time zone DEFAULT now() NOT NULL,
	"completed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_payouts_org_reference" UNIQUE("organization_id","reference")
);
--> statement-breakpoint
CREATE TABLE "tax_periods" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "tax_periods_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"period" text NOT NULL,
	"year" smallint NOT NULL,
	"due_at" date NOT NULL,
	"sales_satang" bigint NOT NULL,
	"vat_satang" bigint NOT NULL,
	"wht_satang" bigint DEFAULT 0 NOT NULL,
	"remitted_satang" bigint DEFAULT 0 NOT NULL,
	"currency" char(3) DEFAULT 'THB' NOT NULL,
	"status" "tax_status" DEFAULT 'upcoming' NOT NULL,
	"filed_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	CONSTRAINT "uq_tax_periods_org_period" UNIQUE("organization_id","period","year")
);
--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_order_id_orders_id_fk" FOREIGN KEY ("order_id") REFERENCES "public"."orders"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "invoices" ADD CONSTRAINT "invoices_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payout_items" ADD CONSTRAINT "payout_items_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payout_items" ADD CONSTRAINT "payout_items_payout_id_payouts_id_fk" FOREIGN KEY ("payout_id") REFERENCES "public"."payouts"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payout_items" ADD CONSTRAINT "payout_items_payment_id_payments_id_fk" FOREIGN KEY ("payment_id") REFERENCES "public"."payments"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "payouts" ADD CONSTRAINT "payouts_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "tax_periods" ADD CONSTRAINT "tax_periods_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_invoices_order" ON "invoices" USING btree ("order_id");--> statement-breakpoint
CREATE INDEX "ix_invoices_event" ON "invoices" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "ix_invoices_status" ON "invoices" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "ix_payout_items_payout" ON "payout_items" USING btree ("payout_id");--> statement-breakpoint
CREATE INDEX "ix_payout_items_payment" ON "payout_items" USING btree ("payment_id");--> statement-breakpoint
CREATE INDEX "ix_payouts_status" ON "payouts" USING btree ("organization_id","status");--> statement-breakpoint
CREATE INDEX "ix_payouts_event" ON "payouts" USING btree ("event_id");--> statement-breakpoint
CREATE INDEX "ix_tax_periods_org" ON "tax_periods" USING btree ("organization_id");