CREATE TYPE "public"."check_in_method" AS ENUM('qr', 'manual', 'upload');--> statement-breakpoint
CREATE TYPE "public"."scan_outcome" AS ENUM('admitted', 'already_checked_in', 'invalid', 'wrong_event', 'cancelled');--> statement-breakpoint
CREATE TABLE "check_ins" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "check_ins_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"organization_id" bigint NOT NULL,
	"event_id" uuid NOT NULL,
	"ticket_id" uuid NOT NULL,
	"attendee_id" bigint,
	"checked_in_at" timestamp with time zone DEFAULT now() NOT NULL,
	"method" "check_in_method" NOT NULL,
	"checked_in_by" uuid,
	"station_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "uq_check_ins_ticket" UNIQUE("ticket_id")
);
--> statement-breakpoint
ALTER TABLE "check_ins" ADD CONSTRAINT "check_ins_organization_id_organizations_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organizations"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "check_ins" ADD CONSTRAINT "check_ins_event_id_events_id_fk" FOREIGN KEY ("event_id") REFERENCES "public"."events"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "check_ins" ADD CONSTRAINT "check_ins_ticket_id_tickets_id_fk" FOREIGN KEY ("ticket_id") REFERENCES "public"."tickets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "check_ins" ADD CONSTRAINT "check_ins_attendee_id_attendees_id_fk" FOREIGN KEY ("attendee_id") REFERENCES "public"."attendees"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "check_ins" ADD CONSTRAINT "check_ins_checked_in_by_users_id_fk" FOREIGN KEY ("checked_in_by") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "ix_check_ins_event" ON "check_ins" USING btree ("organization_id","event_id");--> statement-breakpoint
CREATE INDEX "ix_check_ins_feed" ON "check_ins" USING btree ("event_id","checked_in_at");--> statement-breakpoint
CREATE INDEX "ix_check_ins_attendee" ON "check_ins" USING btree ("attendee_id");