-- Every scan the door made, and what it decided (US-REG-12; erd.md
-- "Designed but not built").
--
-- 0039 created the `scan_outcome` enum (`admitted`, `already_checked_in`,
-- `invalid`, `wrong_event`, `cancelled`) and then gave it no column: a query
-- for `information_schema.columns WHERE udt_name = 'scan_outcome'` returned
-- zero rows until this migration. So a bad QR, a pass for another event or a
-- refunded ticket turned away at the door left no trace whatsoever — no count,
-- nothing to settle a disputed entry with, and no way at all to tell a quiet
-- night from a scanner that had stopped working. This table is where that
-- enum finally lands.
--
-- WHY NOT `check_ins`. The obvious move is a column on the table that already
-- exists, and the ERD proposed exactly that (`check_ins.state`,
-- `.other_event_id`, `.scanned_qr`). It cannot work. `uq_check_ins_ticket` is
-- a UNIQUE on `ticket_id` alone, and that constraint is the entire concurrency
-- story of the door: two staff scanning one code both insert, one wins, and
-- the loser reads back the winner's arrival time instead of admitting a second
-- person. One row per ticket is the guarantee. A refusal is not one row per
-- ticket — the same damaged pass is presented five times in a minute, and an
-- unknown code has no ticket to be unique on at all, so `ticket_id` could not
-- stay `NOT NULL` either. Widening that table would have to weaken the one
-- constraint protecting the admission. That conflict is almost certainly why
-- the columns were drawn and never built.
--
-- WHY ATTEMPTS, NOT REFUSALS. This records admissions too, including the
-- `already_checked_in` ones. A table of refusals alone has no denominator: "19
-- invalid scans" is unreadable without the 1,340 that worked, and a refusal
-- RATE is the number that distinguishes a busy door from a broken one.
-- `check_ins` stays exactly as it was and keeps being the source of truth for
-- who is inside — this ledger is additive, and an admission writes both rows
-- in one transaction so neither can exist without the other.
--
-- It is also APPEND-ONLY, which is what makes it evidence. Undoing a check-in
-- DELETEs the `check_ins` row, because an admission that was reversed did not
-- happen; the `admitted` row here survives, because the scan did happen. The
-- two tables answer different questions: `check_ins` is the state of the room,
-- this is the history of the door. Nothing here is ever updated or deleted,
-- which is a property of the only writer (`CheckInRepository` has no update or
-- delete path for it) rather than something the schema enforces — a REVOKE
-- would not bind the app, which connects as the schema owner, for the same
-- reason the RLS policy below is defence in depth and not the guarantee.
--
-- WHY A FINGERPRINT AND NOT THE TOKEN. `token_fingerprint` is a SHA-256 digest
-- of the code presented, never the code. `tickets.qr_token` is a bearer
-- credential: holding that string is the entitlement to walk in. This table is
-- append-only, outlives both the event and the ticket, and is readable by
-- everyone who may work or review a door — so raw tokens in it would make a
-- door-incident log into a list of working passes, and an export of it a set
-- of usable tickets. The digest costs nothing we need: a recognised code
-- already carries its `ticket_id`, so "was this ticket turned away?" never
-- needed the token; grouping on the digest still separates "one damaged pass
-- presented forty times" from "forty different bad codes", which is the
-- difference between a broken ticket and somebody probing the door; and "was
-- THIS code presented?" stays a lookup, because whoever holds the code can
-- hash it the same way. The digest is genuinely one-way here, because a token
-- is 24 characters drawn from a 32-symbol alphabet (~120 bits) and there is no
-- dictionary to walk back through. Storing a credential as a digest is already
-- this schema's answer elsewhere, in `api_keys.key_hash`. NULL means no code
-- was presented at all, which is precisely what a manual admission is.
--
-- `ticket_event_id` is the ERD's `other_event_id`, kept only when it differs
-- from `event_id`: that is the single thing a `wrong_event` refusal is about,
-- and leaving it NULL on every other outcome is what lets
-- `ticket_event_id IS NOT NULL` read as "a pass for somewhere else turned up
-- here" rather than also matching the rows where it would merely repeat the
-- event we already know.
CREATE TABLE IF NOT EXISTS "scan_attempts" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" bigint NOT NULL REFERENCES "organizations"("id") ON DELETE CASCADE,
  -- RESTRICT, matching the choice 0041 made for `check_ins.event_id`: what
  -- happened at a door is history, and it must outlive the event row rather
  -- than being erased along with it.
  "event_id" uuid NOT NULL REFERENCES "events"("id") ON DELETE RESTRICT,
  "outcome" "scan_outcome" NOT NULL,
  "method" "check_in_method" NOT NULL,
  -- NULL for an unrecognised code, which is the commonest refusal and has no
  -- ticket to point at. SET NULL rather than CASCADE or RESTRICT on delete:
  -- CASCADE would let erasing a ticket erase the evidence that it was refused,
  -- while RESTRICT would block the hard deletes that account erasure and the
  -- e2e fixtures both perform. Losing the pointer still leaves the outcome,
  -- the time, the station and the fingerprint.
  "ticket_id" uuid REFERENCES "tickets"("id") ON DELETE SET NULL,
  -- Which event the presented pass actually belonged to; see the header. SET
  -- NULL, not RESTRICT, because this is a secondary reference and deleting
  -- some OTHER event should not be blocked by a refusal recorded here.
  "ticket_event_id" uuid REFERENCES "events"("id") ON DELETE SET NULL,
  "token_fingerprint" text,
  -- Which door read it, for reconciling a busy entrance.
  "station_id" text,
  -- The staff member who scanned; NULL once that account is removed.
  "scanned_by" uuid REFERENCES "users"("id") ON DELETE SET NULL,
  -- When the scan happened, which an offline replay may backdate, as against
  -- `created_at` = when the row reached us. `message_deliveries` splits
  -- `sent_at` from `created_at` for the same reason.
  "scanned_at" timestamptz NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT now()
);
--> statement-breakpoint
-- The door-incident report reads one event's night newest-first. Counts per
-- outcome come off this same index and are filtered, rather than getting an
-- index of their own: an event's whole night is a few thousand rows, so a
-- second index would be paid on every single scan to save a filter over a set
-- that small.
CREATE INDEX IF NOT EXISTS "ix_scan_attempts_event"
  ON "scan_attempts" USING btree ("organization_id", "event_id", "scanned_at");
--> statement-breakpoint
-- "Was it one broken pass or forty different bad codes?" — the question the
-- fingerprint exists to answer, and a GROUP BY needs the index to answer it.
CREATE INDEX IF NOT EXISTS "ix_scan_attempts_token"
  ON "scan_attempts" USING btree ("organization_id", "token_fingerprint");
--> statement-breakpoint
-- Settling one disputed entry: every scan this ticket was ever part of.
CREATE INDEX IF NOT EXISTS "ix_scan_attempts_ticket"
  ON "scan_attempts" USING btree ("ticket_id");
--> statement-breakpoint
-- Tenant isolation, matching every other tenant table. Defence in depth: the
-- repository also scopes by organization_id, because the app connects as the
-- schema owner and Postgres skips RLS for that role.
DO $$
BEGIN
  EXECUTE 'ALTER TABLE scan_attempts ENABLE ROW LEVEL SECURITY';
  EXECUTE
    'CREATE POLICY tenant_isolation ON scan_attempts FOR ALL '
    'USING (organization_id = current_setting(''app.current_org'', true)::bigint) '
    'WITH CHECK (organization_id = current_setting(''app.current_org'', true)::bigint)';
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
